version: '3.8'

services:
  db:
    image: postgres:16
    container_name: Task8
    environment:
      POSTGRES_DB: task8db  # Имя базы данных
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - task8-network

networks:
  task8-network:
    driver: bridge

volumes:
  db-data:
