name: Homework Java CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'Homework/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Homework/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      # 1. Checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Сборка проекта
      - name: Build project
        run: ./gradlew build

      # 4. Прогон тестов и генерация отчёта о покрытии
      - name: Run tests and generate coverage report
        run: ./gradlew test jacocoTestReport

      # 5. Публикация отчёта о покрытии
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html/

      # 6. Статический анализ кода
      - name: Static Code Analysis - Checkstyle
        run: ./gradlew checkstyleMain

      # 7. Логин в GitHub Docker Registry
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 8. Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/homework:${{ github.sha }} .

      # 9. Публикация Docker-образа в GitHub Packages
      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository }}/homework:${{ github.sha }}

      # 10. Завершение workflow
      - name: Complete Job
        run: echo "Workflow completed for the entire project"
